services:
  web:
    image: fastapi_app
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
  pgdb:
    image: postgres:latest
    container_name: postgres_db
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql

volumes:
  local_pgdata:
    driver: local
